version: "2"
services:
  console-lorawan-api-go:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: bash -c "cd go && make all"
    volumes:
      - ./:/console-lorawan-api
  console-lorawan-api-swagger:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: bash -c "cd swagger && make all"
    volumes:
      - ./:/console-lorawan-api
  
